version: '3.8'

networks:
  boilerplate_network:
    driver: bridge

services:
  mysqldb:
    networks:
      - boilerplate_network
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:$DB_PORT

  app:
    networks:
    - boilerplate_network
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:$APP_PORT
    environment:
      - DB_CLIENT=$DB_CLIENT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysqldb
    links:
      - mysqldb:mysqldb
    ports:
      - 9000:80
    restart: always